### ISSUE TITLE
Consider using IHttpClientFactory

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [SlyCedix/dotNETLemmy#2]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0

As the scope is not defined (singleton, scoped per client, scoped per request) for this library- it is possible for users to consume this package, creating a client per request.

If this occurs, httpclient resources may not be properly released, causing potential socket exhaustion.

IHttpClientFactory contains intelligence to reuse sockets, and can be requested in the constructor of LemmyHttpClient. This would allow sockets to be gracefully reused.

**Comment by SlyCedix** [comment]
Good call, I was toying with the idea of using DI for the actual LemmyHttpClient object but figured that if users didn't want to use DI it may be a headache for that. Using DI for the HttpClientFactory is a better approach for handling those resources, thanks!

**Comment by SlyCedix** [comment]
Added in #3, as a typed client
